### ISSUE TITLE
Unfortunately, I was not able to get your answers, because of the following error:\n\n'NoneType' object has no attribute 'type'\n

### ISSUE THREAD

**Issue by nothk** [Sinaptik-AI/pandas-ai#1054]
### System Info

windows 10, 
python 3.9.5

### 🐛 Describe the bug

I run this default code, but get error 
"Unfortunately, I was not able to get your answers, because of the following error:\n\n'NoneType' object has no attribute 'type'\n"

I did something wrong? what should I do?

thanks

```
import os
import pandas as pd
from pandasai import SmartDataframe

sales_by_country = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})

# I get my API key from https://www.pandabi.ai/admin/api-keys, it's free? this API can provide LLM function?
# I replaced YOUR_API_KEY by API_key from https://www.pandabi.ai/admin/api-keys
os.environ["PANDASAI_API_KEY"] = "YOUR_API_KEY"

agent = SmartDataframe(sales_by_country)
agent.chat('Which are the top 5 countries by sales?')
```

**Comment by ysh-core42** [comment]
same problem here, on Mac, python 3.9

**Comment by YarShev** [comment]
Hi @nothk and @ysh-core42, could you tell us what version of pandas-ai you are experiencing the issue with?

**Comment by nothk** [comment]
> Hi @nothk and @ysh-core42, could you tell us what version of pandas-ai you are experiencing the issue with?

pandasai.__version__
2.0.21

**Comment by thekakodkar** [comment]
Same error on Windows 11 Enterprise , python 3.10.11 ; panadasai 2.0.3

**Comment by YarShev** [comment]
The issue doesn't seem to be related to the upgrading pandas version. @gventuri, any insight on this?

**Comment by YarShev** [comment]
I see the same error with pandasai==2.0.16 if I install pandasai with pip. However, if I work with main branch and install dependencies with poetry the code example passes. It is really confusing. @gventuri, might it be a case that PyPI package is missing some necessary files?

**Comment by thekakodkar** [comment]
I tried to update the extra dependencies using pip install pandasai[streamlit] after which the error I get now is " 'NoneType' object has no attribute 'call'

**Comment by YarShev** [comment]
I looked into the code and found the place where the error is raised, the line is. https://github.com/Sinaptik-AI/pandas-ai/blob/5d4753a2b46d968559ec1132af2f5f511bea45e7/pandasai/agent/base.py#L254

PyPI pandasai package is missing [pandasai.json](https://github.com/Sinaptik-AI/pandas-ai/blob/main/pandasai.json) file, where the config is loaded from. Since there is no this file, `self.context.config.llm` is None and thus when accesing `self.context.config.llm.type` the error is raised.

```bash
'NoneType' object has no attribute 'type'
```

I am not sure if the file is not present intentionally so letting @gventuri shed light on this.

**Comment by YarShev** [comment]
Just as a workaround you could place [pandasai.json](https://github.com/Sinaptik-AI/pandas-ai/blob/main/pandasai.json) file in the root directory of the installed pandasai package.

**Comment by thekakodkar** [comment]
I tried adding the json file, upgraded the pandasai; still gives me "ValueError: Invalid input data. We cannot convert it to a dataframe."

**Comment by YarShev** [comment]
Indeed, this workaround doesn't seem to be working. I got `AttributeError: module 'pandasai.llm' has no attribute 'BambooLLM'`. Let's wait for a response from a maintainer.

**Comment by sanjivjha** [comment]
I am also getting the same error, installed latest pandasai

**Comment by qcxia20** [comment]
> Just as a workaround you could place [pandasai.json](https://github.com/Sinaptik-AI/pandas-ai/blob/main/pandasai.json) file in the root directory of the installed pandasai package.

This is right. Just want to supplement that the root directory is by default **current directory**.
https://github.com/Sinaptik-AI/pandas-ai/blob/5d4753a2b46d968559ec1132af2f5f511bea45e7/pandasai/helpers/path.py#L11-L25
So you may need to set the environment variable **PANDASAI_WORKSPACE** and ensure that path has [pandasai.json](https://github.com/Sinaptik-AI/pandas-ai/blob/main/pandasai.json).

**Comment by rafabelokurows** [comment]
I had the same issue, but creating a environment variable named PANDASAI_WORKSPACE and pointing to a directory where pandasai.json was made it work for me :) 
Thanks @YarShev and @qcxia20

**Comment by Valdegg** [comment]
Adding the env file and the json made pandasai work for some cases, but I still get absurd errors, such as:

Unfortunately, I was not able to answer your question, because of the following error:

'type'


Executing "sdf.last_code_generated" works though... So it's some bug in the chat pipeline?

**Comment by gventuri** [comment]
Try to upgrade to 2.0.22, should be fixed now! Closing :)

**Comment by thekakodkar** [comment]
Not sure if its related but after I upgrade the pandasai to 2.0.23, I get the below error

Request failed: HTTPSConnectionPool(host='api.domer.ai', port=443): Max retries exceeded with url: /api/training-data/qa/relevant-qa?query=%23%23%23+QUERY%0A+How+many+loans+are+from+men+and+have+been+paid+off%3F&count=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

**Comment by Riofd** [comment]
> Try to upgrade to 2.0.22, should be fixed now! Closing :)

Sorry to disturb you again. I still have the same error in 2.0.24. I want to know how to solve this now.

**Comment by PedroGarcia0202** [comment]
Today i receive this error in pandasia 2.0.25. Some new solution ?

**Comment by jaiminee** [comment]
> 2.0.22

Hi, I upgraded to this version but getting this error ( running code in Amazon Sagemaker Jupyterlab)
<img width="1011" alt="Screenshot 2024-03-27 at 12 29 13 PM" src="https://github.com/Sinaptik-AI/pandas-ai/assets/31419752/65251de9-d703-411e-943a-e826c4baa185">
<img width="1010" alt="Screenshot 2024-03-27 at 12 30 33 PM" src="https://github.com/Sinaptik-AI/pandas-ai/assets/31419752/3007ad3e-018f-4e4d-984a-e155dc102a12">

**Comment by Riofd** [comment]
> > Try to upgrade to 2.0.22, should be fixed now! Closing :)
> 
> Sorry to disturb you again. I still have the same error in 2.0.24. I want to know how to solve this now.

When I use the openai model, it works well. So I suppose the reason is my pandasai account has no billing or access.

**Comment by ArslanSaleem** [comment]
Hi @nothk,

I encountered this issue in Jupyter Notebooks. Strangely, llm was None, although it wasn't the case when running from a .py file.

This PR should fix the issue
https://github.com/Sinaptik-AI/pandas-ai/pull/1070

**Comment by ArslanSaleem** [comment]
@flashtheman,

How did you verify that? Did you check out my branch or did you find it through pip? Please note that the fix PR has not been released yet.
